# Numpy - Numerical Python

In [1]:
#import librabry
import numpy as np

In [7]:
arr = np.array([[1,2,3,4],[2,5,6,9]])
arr

array([[1, 2, 3, 4],
       [2, 5, 6, 9]])

In [9]:
arr[0][1]

2

In [10]:
arr[1][3]

9

In [17]:
#dimension of array

print(arr.ndim)
print(arr.shape)
print(arr.data)
print(arr.size)
print(type(arr))

2
(2, 4)
8
<class 'numpy.ndarray'>


# Random number generator using numpy


In [2]:
from numpy import random
x=random.randint(100,size=(3,3))
x

array([[ 3, 88, 23],
       [30, 59, 13],
       [76, 81, 56]])

In [3]:
y=random.rand(20)
y

array([0.74436496, 0.91186966, 0.39572056, 0.90129633, 0.53142256,
       0.55667924, 0.96511252, 0.99202251, 0.04153565, 0.16923838,
       0.418984  , 0.15657267, 0.48171232, 0.35517044, 0.13562177,
       0.37057466, 0.25570966, 0.17894462, 0.71329965, 0.97029464])

In [4]:
z=random.random((2,3))
z

array([[0.30574492, 0.02614448, 0.68566506],
       [0.94596582, 0.20754906, 0.92206523]])

In [40]:

x=random.randint(100,size=(3,3))
random.seed(50)
x

array([[48, 96, 11],
       [33, 94,  4],
       [70, 70, 22]])

# numpy function 

In [39]:
#zero matrix
import numpy as np
zero=np.zeros((2,2))
zero

array([[0., 0.],
       [0., 0.]])

In [11]:
#one matrix
h=np.ones((3,3))
h

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
#indentity matrix
idt = np.eye((3))
idt

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
#create constant matrix
A = np.full((3,3),5)
A

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

# array indexing and slicing

In [47]:
arr = np.array([[1,2,3,4],[2,5,6,9],[5,8,7,9]])
arr


array([[1, 2, 3, 4],
       [2, 5, 6, 9],
       [5, 8, 7, 9]])

In [48]:
arr[1]

array([2, 5, 6, 9])

a[0][0]a[0][1]a[0][2]

a[1][0]a[1][0]a[1][2]

a[2][0]a[2][0]a[2][2]

In [49]:
arr[0][1]=3
arr

array([[1, 3, 3, 4],
       [2, 5, 6, 9],
       [5, 8, 7, 9]])

In [54]:
#slicing
#slicing of rows ,slicing of coloum
#[st:end, st:end]
arr[2: ,0:]

array([[5, 8, 7, 9]])

In [59]:
arr1 = np.full((3,4),2)
arr1

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

# array broad casting

In [60]:
print(arr,'\n\n',arr1)

[[1 3 3 4]
 [2 5 6 9]
 [5 8 7 9]] 

 [[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [65]:
# addition of matrix
print(arr+arr1)
print(np.add(arr,arr1))

[[ 3  5  5  6]
 [ 4  7  8 11]
 [ 7 10  9 11]]
[[ 3  5  5  6]
 [ 4  7  8 11]
 [ 7 10  9 11]]


In [69]:
#print(arr-arr1)
print(np.subtract(arr,arr1))

[[-1  1  1  2]
 [ 0  3  4  7]
 [ 3  6  5  7]]


In [71]:
#squar root
sq=np.sqrt(arr1)
sq

array([[1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.41421356, 1.41421356]])

In [72]:
np.sum(sq)

16.970562748477143

In [73]:
np.sum(sq,axis=1)

array([5.65685425, 5.65685425, 5.65685425])

In [75]:
np.sum(arr1)

24

# calculate BMI of players

In [77]:
#height of player in inch

h_in = [55,88,99,45,75,45,46,42,42,15,15]
ht_np=np.array(h_in)
ht_np

array([55, 88, 99, 45, 75, 45, 46, 42, 42, 15, 15])

In [82]:
#convert inch into meter
ht_np=ht_np*0.0245
ht_np

array([0.00080884, 0.00129414, 0.00145591, 0.00066178, 0.00110296,
       0.00066178, 0.00067648, 0.00061766, 0.00061766, 0.00022059,
       0.00022059])

In [84]:
#weight of the player
wt_pd=[1000,3000,2000,2000,2000,200,1000,8585,9658,2300,25872]
wt_np = np.array(wt_pd)
#convert in to kg
wt_np = wt_np*0.45
wt_np

array([  450.  ,  1350.  ,   900.  ,   900.  ,   900.  ,    90.  ,
         450.  ,  3863.25,  4346.1 ,  1035.  , 11642.4 ])

In [85]:
#calculate BMI value
bmi = wt_np/ht_np**2
bmi

array([6.87845070e+08, 8.06068441e+08, 4.24595722e+08, 2.05504329e+09,
       7.39815586e+08, 2.05504329e+08, 9.83332389e+08, 1.01264617e+10,
       1.13921220e+10, 2.12696981e+10, 2.39256360e+11])

In [90]:
bmi[bmi<8.06068441e+08]

array([6.87845070e+08, 8.06068441e+08, 4.24595722e+08, 7.39815586e+08,
       2.05504329e+08])

In [94]:
players = np.array([wt_np,ht_np])
players

array([[4.50000000e+02, 1.35000000e+03, 9.00000000e+02, 9.00000000e+02,
        9.00000000e+02, 9.00000000e+01, 4.50000000e+02, 3.86325000e+03,
        4.34610000e+03, 1.03500000e+03, 1.16424000e+04],
       [8.08836875e-04, 1.29413900e-03, 1.45590638e-03, 6.61775625e-04,
        1.10295938e-03, 6.61775625e-04, 6.76481750e-04, 6.17657250e-04,
        6.17657250e-04, 2.20591875e-04, 2.20591875e-04]])

In [95]:
players.shape

(2, 11)

In [99]:
pT = players.T
pT

array([[4.50000000e+02, 8.08836875e-04],
       [1.35000000e+03, 1.29413900e-03],
       [9.00000000e+02, 1.45590638e-03],
       [9.00000000e+02, 6.61775625e-04],
       [9.00000000e+02, 1.10295938e-03],
       [9.00000000e+01, 6.61775625e-04],
       [4.50000000e+02, 6.76481750e-04],
       [3.86325000e+03, 6.17657250e-04],
       [4.34610000e+03, 6.17657250e-04],
       [1.03500000e+03, 2.20591875e-04],
       [1.16424000e+04, 2.20591875e-04]])

In [100]:
pT.shape

(11, 2)

# stastical operation


In [101]:
#min,max,mean,median,std,var,perc,coorcoef


In [110]:
print(np.amax(wt_np))
print(np.amax(ht_np))
print(np.corrcoef(wt_np,ht_np))

11642.4
0.001455906375
[[ 1.         -0.48427637]
 [-0.48427637  1.        ]]


In [111]:
#boolean
bools = [False,True,False,True,False]
bools

[False, True, False, True, False]

In [118]:
b=np.array(bools)
b

array([False,  True, False,  True, False])

In [117]:
b.sum()

2

In [119]:
b.any()

True

In [124]:
b.all()

False

In [126]:
n = np.array(['a','s','a','l','a','a'])
n

array(['a', 's', 'a', 'l', 'a', 'a'], dtype='<U1')

In [127]:
np.unique(n)

array(['a', 'l', 's'], dtype='<U1')